CREATE TABLE PARTICIPANTE (
	NU_INSCRICAO BIGINT(16) NOT NULL,
	NU_ANO INT(4) NULL,
	TP_FAIXA_ETARIA INT(2) NULL,
	TP_SEXO varchar(1) NULL,
	TP_ESTADO_CIVIL INT(1) NULL,
	TP_COR_RACA INT(1) NULL,
	TP_NACIONALIDADE INT(1) NULL,
	TP_ST_CONCLUSAO INT(1) NULL,
	TP_ANO_CONCLUIU INT(2) NULL,
	TP_ESCOLA INT(1) NULL,
	TP_ENSINO INT(1) NULL,
	IN_TREINEIRO varchar(1) NULL,
	CO_MUNICIPIO_ESC INT(7) NULL,
	CO_MUNICIPIO_PROVA INT(7) NULL,
	PRIMARY KEY (NU_INSCRICAO)
);

CREATE TABLE ESCOLA (
	CO_MUNICIPIO_ESC INT(7) NOT NULL,
	NO_MUNICIPIO_ESC varchar(150) NULL,
	CO_UF_ESC INT(2) NULL,
	SG_UF_ESC varchar(2) NULL,
	TP_DEPENDENCIA_ADM_ESC INT(1) NULL,
	TP_LOCALIZACAO_ESC INT(1) NULL,
	TP_SIT_FUNC_ESC INT(1) NULL,
	PRIMARY KEY (CO_MUNICIPIO_ESC)
);

CREATE TABLE LOCAL_PROVA (
	CO_MUNICIPIO_PROVA INT(7) NOT NULL,
	NO_MUNICIPIO_PROVA varchar(150) NULL,
	CO_UF_PROVA varchar(2) NULL,
	SG_UF_PROVA varchar(2) NULL,
	PRIMARY KEY (CO_MUNICIPIO_PROVA)
);

CREATE TABLE PROVA_OBJETIVA (
	ID SERIAL,
	TP_PRESENCA_CN INT(1) NULL,
	TP_PRESENCA_CH INT(1) NULL,
	TP_PRESENCA_LC INT(1) NULL,
	TP_PRESENCA_MT INT(1) NULL,
	CO_PROVA_CN INT(3) NULL,
	CO_PROVA_CH INT(3) NULL,
	CO_PROVA_LC INT(3) NULL,
	CO_PROVA_MT INT(3) NULL,
	NU_NOTA_CN INT(9) NULL,
	NU_NOTA_CH INT(9) NULL,
	NU_NOTA_LC INT(9) NULL,
	NU_NOTA_MT INT(9) NULL,
	TX_RESPOSTAS_CN varchar(50) NULL,
	TX_RESPOSTAS_CH varchar(50) NULL,
	TX_RESPOSTAS_LC varchar(50) NULL,
	TX_RESPOSTAS_MT varchar(50) NULL,
	TP_LINGUA INT(1) NULL,
	TX_GABARITO_CN varchar(50) NULL,
	TX_GABARITO_CH varchar(50) NULL,
	TX_GABARITO_LC varchar(50) NULL,
	TX_GABARITO_MT varchar(50) NULL,
	NU_INSCRICAO BIGINT(16) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE REDACAO (
	ID SERIAL,
	TP_STATUS_REDACAO INT(1) NULL,
	NU_NOTA_COMP1 INT(9) NULL,
	NU_NOTA_COMP2 INT(9) NULL,
	NU_NOTA_COMP3 INT(9) NULL,
	NU_NOTA_COMP4 INT(9) NULL,
	NU_NOTA_COMP5 INT(9) NULL,
	NU_NOTA_REDACAO INT(9) NULL,
	NU_INSCRICAO BIGINT(16) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE QUESTIONARIO (
	ID SERIAL,
	Q001 varchar(1) NULL,
	Q002 varchar(1) NULL,
	Q003 varchar(1) NULL,
	Q004 varchar(1) NULL,
	Q005 INT(2) NULL,
	Q006 varchar(1) NULL,
	Q007 varchar(1) NULL,
	Q008 varchar(1) NULL,
	Q009 varchar(1) NULL,
	Q010 varchar(1) NULL,
	Q011 varchar(1) NULL,
	Q012 varchar(1) NULL,
	Q013 varchar(1) NULL,
	Q014 varchar(1) NULL,
	Q015 varchar(1) NULL,
	Q016 varchar(1) NULL,
	Q017 varchar(1) NULL,
	Q018 varchar(1) NULL,
	Q019 varchar(1) NULL,
	Q020 varchar(1) NULL,
	Q021 varchar(1) NULL,
	Q022 varchar(1) NULL,
	Q023 varchar(1) NULL,
	Q024 varchar(1) NULL,
	Q025 varchar(1) NULL,
	NU_INSCRICAO BIGINT(16) NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE PARTICIPANTE ADD CONSTRAINT PARTICIPANTE_fk0 FOREIGN KEY (CO_MUNICIPIO_ESC) REFERENCES ESCOLA(CO_MUNICIPIO_ESC);

ALTER TABLE PARTICIPANTE ADD CONSTRAINT PARTICIPANTE_fk1 FOREIGN KEY (CO_MUNICIPIO_PROVA) REFERENCES LOCAL_PROVA(CO_MUNICIPIO_PROVA);

ALTER TABLE PROVA_OBJETIVA ADD CONSTRAINT PROVA_OBJETIVA_fk0 FOREIGN KEY (NU_INSCRICAO) REFERENCES PARTICIPANTE(NU_INSCRICAO);

ALTER TABLE REDACAO ADD CONSTRAINT REDACAO_fk0 FOREIGN KEY (NU_INSCRICAO) REFERENCES PARTICIPANTE(NU_INSCRICAO);

ALTER TABLE QUESTIONARIO ADD CONSTRAINT QUESTIONARIO_fk0 FOREIGN KEY (NU_INSCRICAO) REFERENCES PARTICIPANTE(NU_INSCRICAO);